import { h } from 'https://cdn.skypack.dev/preact';

export { render } from 'https://cdn.skypack.dev/preact';
export const define = (tag) => (attrs, ...childs) => {
    return h(tag, attrs, childs);
}

const HTML_TAGS = (() => {
    let tags = {};
    let list = [
        // Main root
        "html",
        // Document metadata
        "base",
        "head",
        "link",
        "meta",
        "style",
        "title",
        // Sectioning root
        "body",
        // Content sectioning
        "address",
        "article",
        "aside",
        "footer",
        "header",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hggroup",
        "main",
        "nav",
        "section",
        // Text content
        "blockquote",
        "dd",
        "div",
        "dl",
        "dt",
        "figcaption",
        "figure",
        "hr",
        "li",
        "ol",
        "p",
        "pre",
        "ul",
        // Inline text semantics
        "a",
        "abbr",
        "b",
        "bdi",
        "bdo",
        "br",
        "cite",
        "code",
        "data",
        "dfn",
        "em",
        "i",
        "kbd",
        "mark",
        "q",
        "rb",
        "rp",
        "rt",
        "rtc",
        "ruby",
        "s",
        "samp",
        "small",
        "span",
        "strong",
        "sub",
        "sup",
        "time",
        "u",
        "variable",
        "wbr",
        // Image and multimedia
        "area",
        "audio",
        "img",
        "map",
        "track",
        "video",
        // Embedded content
        "embed",
        "iframe",
        "object",
        "param",
        "picture",
        "source",
        // Scripting
        "canvas",
        "noscript",
        "script",
        // Demarcating edits
        "del",
        "ins",
        // Table content
        "caption",
        "col",
        "colgroup",
        "table",
        "tbody",
        "td",
        "tfoot",
        "th",
        "thead",
        "tr",
        // Forms
        "button",
        "datalist",
        "fieldset",
        "form",
        "input",
        "label",
        "legend",
        "meter",
        "oprgroup",
        "option",
        "output",
        "progress",
        "select",
        "textarea",
        // Interactive elements
        "details",
        "dialog",
        "menu",
        "summary",
        // Web Components
        "slot",
        "template"
    ];
    list.forEach((tag) => {
        tags[tag] = define(tag);
    });
    return tags;
})();


export const {
    html,
    base,
    head,
    link,
    meta,
    style,
    title,
    body,
    address,
    article,
    aside,
    footer,
    header,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    hggroup,
    main,
    nav,
    section,
    blockquote,
    dd,
    div,
    dl,
    dt,
    figcaption,
    figure,
    hr,
    li,
    ol,
    p,
    pre,
    ul,
    a,
    abbr,
    b,
    bdi,
    bdo,
    br,
    cite,
    code,
    data,
    dfn,
    em,
    i,
    kbd,
    mark,
    q,
    rb,
    rp,
    rt,
    rtc,
    ruby,
    s,
    samp,
    small,
    span,
    strong,
    sub,
    sup,
    time,
    u,
    variable,
    wbr,
    area,
    audio,
    img,
    map,
    track,
    video,
    embed,
    iframe,
    object,
    param,
    picture,
    source,
    canvas,
    noscript,
    script,
    del,
    ins,
    caption,
    col,
    colgroup,
    table,
    tbody,
    td,
    tfoot,
    th,
    thead,
    tr,
    button,
    datalist,
    fieldset,
    form,
    input,
    label,
    legend,
    meter,
    oprgroup,
    option,
    output,
    progress,
    select,
    textarea,
    details,
    dialog,
    menu,
    summary,
    slot,
    template
} = HTML_TAGS;